from datetime import datetime
from typing import Protocol

from app.models import Sample, Tag


class Store(Protocol):
    name: str

    async def ping(self) -> None: ...
    async def write(self, samples: list[Sample]) -> None: ...
    async def locf(self, tag_ids: list[int], at: datetime) -> list[Sample]: ...
    async def range(self, tag_ids: list[int], start: datetime, end: datetime) -> list[Sample]: ...
    async def upsert_tags(self, tags: list[Tag]) -> None: ...
    async def list_tags(self) -> list[Tag]: ...
    async def close(self) -> None: ...
