apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: prism
    secureJsonData:
      password: prism
    jsonData:
      database: prism
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: false

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: prism
      protocol: http
      username: prism
    secureJsonData:
      password: prism
    editable: false

  - name: QuestDB
    uid: questdb
    type: postgres
    access: proxy
    url: questdb:8812
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      database: qdb
      sslmode: disable
      postgresVersion: 1500
    editable: false

  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: prism
      defaultBucket: prism
      tlsSkipVerify: true
    secureJsonData:
      token: prism-dev-token
    editable: false

  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: false
