global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: go-api
    static_configs:
      - targets: ["go-api:8081"]
        labels:
          backend: go
          layer: api

  - job_name: python-api
    static_configs:
      - targets: ["python-api:8082"]
        labels:
          backend: python
          layer: api

  - job_name: timescaledb
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          storage: timescaledb
          layer: db

  - job_name: clickhouse
    static_configs:
      - targets: ["clickhouse:9363"]
        labels:
          storage: clickhouse
          layer: db

  - job_name: influxdb
    static_configs:
      - targets: ["influxdb:8086"]
        labels:
          storage: influxdb
          layer: db

  - job_name: victoriametrics
    static_configs:
      - targets: ["victoriametrics:8428"]
        labels:
          storage: victoriametrics
          layer: db

  - job_name: nats
    metrics_path: /metrics
    static_configs:
      - targets: ["nats:8222"]
        labels:
          layer: bus
