global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: go-api
    static_configs:
      - targets: ["go-api:8081"]
        labels:
          backend: go
          layer: api

  - job_name: csharp-api
    static_configs:
      - targets: ["csharp-api:8083"]
        labels:
          backend: csharp
          layer: api

  - job_name: rust-api
    static_configs:
      - targets: ["rust-api:8084"]
        labels:
          backend: rust
          layer: api

  - job_name: timescaledb
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          storage: timescaledb
          layer: db

  - job_name: questdb
    static_configs:
      - targets: ["questdb:9003"]
        labels:
          storage: questdb
          layer: db

  - job_name: victoriametrics
    static_configs:
      - targets: ["victoriametrics:8428"]
        labels:
          storage: victoriametrics
          layer: db

  - job_name: nats
    metrics_path: /metrics
    static_configs:
      - targets: ["nats:8222"]
        labels:
          layer: bus
