<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Prism.Api</RootNamespace>
    <AssemblyName>Prism.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" Version="7.14.0" />
    <PackageReference Include="NATS.Net" Version="2.6.11" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
  </ItemGroup>
</Project>
